---
title: 'BRT -> eBird'
output:
  pdf_document: default
  html_notebook: default
  html_document: default
---

**You Will Need:**

* The current raster stack

* Your duck species training and test sets

* R packages: raster, gbm, dismo

```{r}
source("Y:/users/rah/R/Rconfigure_default.r")
library(knitr)
library(raster)
library(gbm)
library(dismo)
knitr::opts_knit$set(root.dir = "Y:/users/rah/Teaching/2018fa_fw599/GroupProject/FW599")
```

```{r}
load("Y:/users/rah/Teaching/2018fa_fw599/GroupProject/FW599/trainData_Oxyura_jamaicensis.RData") # trainData
load("Y:/users/rah/Teaching/2018fa_fw599/GroupProject/FW599/testData_Oxyura_jamaicensis.RData") # testData
load("Y:/users/rah/Teaching/2018fa_fw599/GroupProject/FW599/testSubset_Oxyura_jamaicensis.RData") # testSubset
```

```{r}
load("Y:/users/rah/Teaching/2018fa_fw599/GroupProject/FW599/envStack_v3.RData") # envStack
```

```{r}
testSubset = cbind(testSubset,
                  extract(envStack,testSubset[,c(4,3)]))
testSubset$glwd_3 = as.factor(testSubset$glwd_3)
testSubset$GlobCover2009LC = as.factor(testSubset$GlobCover2009LC)
testSubset$LC_5min_global_2012 = as.factor(testSubset$LC_5min_global_2012)
```

```{r}
testData = cbind(testData,
                  extract(envStack,testData[,c(4,3)]))
testData$glwd_3 = as.factor(testData$glwd_3)
testData$GlobCover2009LC = as.factor(testData$GlobCover2009LC)
testData$LC_5min_global_2012 = as.factor(testData$LC_5min_global_2012)
```

```{r}
trainData = cbind(trainData,
                  extract(envStack,trainData[,c(4,3)]))
trainData$glwd_3 = as.factor(trainData$glwd_3)
trainData$GlobCover2009LC = as.factor(trainData$GlobCover2009LC)
trainData$LC_5min_global_2012 = as.factor(trainData$LC_5min_global_2012)
```

```{r}
trainData = rbind(trainData[which(trainData$presAbs==1),], # all presences
                  trainData[sample(which(trainData$presAbs==0),20000),]) # 20000 absences
```

```{r}
PAmodel1 = gbm.step(data=trainData,
                  gbm.x=c(8,12,13,14,15,17,23:45),
                  gbm.y=21,
                  family = "bernoulli", 
                  tree.complexity = 2, 
                  learning.rate = 0.001, 
                  bag.fraction = 0.5)
names(PAmodel1)
summary(PAmodel1)
```
